const economicsQuestions = [
  { text: "GDP stands for?", options: ["Gross Domestic Product", "General Domestic Price", "Global Development Plan", "Gross Development Price"], correct: 0 },
  { text: "Who regulates India's monetary policy?", options: ["SEBI", "RBI", "NITI Aayog", "IMF"], correct: 1 },
  { text: "Inflation means?", options: ["Rise in prices", "Fall in prices", "No change", "Rise in wages"], correct: 0 },
  { text: "RBI stands for?", options: ["Reserve Bank of India", "Regional Bank of India", "Royal Bank of India", "Rural Bank of India"], correct: 0 },
  { text: "GST in India stands for?", options: ["Goods and Services Tax", "General Sales Tax", "Government Service Tax", "Gross Service Tax"], correct: 0 },
  { text: "Which organization regulates stock markets in India?", options: ["RBI", "SEBI", "IRDA", "NABARD"], correct: 1 },
  { text: "Who is known as Father of Economics?", options: ["Karl Marx", "Adam Smith", "John Keynes", "Milton Friedman"], correct: 1 },
  { text: "Fiscal deficit means?", options: ["Govt spends more than it earns", "Govt earns more than it spends", "No spending", "Trade surplus"], correct: 0 },
  { text: "Which currency does Japan use?", options: ["Yuan", "Yen", "Won", "Dollar"], correct: 1 },
  { text: "IMF stands for?", options: ["International Monetary Fund", "Indian Monetary Fund", "International Money Forum", "Internal Market Fund"], correct: 0 },
  { text: "What is a 'Bull Market'?", options: ["Prices rising", "Prices falling", "No change", "Market closed"], correct: 0 },
  { text: "What is a 'Bear Market'?", options: ["Prices rising", "Prices falling", "No change", "Market closed"], correct: 1 },
  { text: "Which is India's central bank?", options: ["SBI", "RBI", "HDFC", "ICICI"], correct: 1 },
  { text: "NITI Aayog replaced which body?", options: ["Planning Commission", "RBI", "SEBI", "Finance Ministry"], correct: 0 },
  { text: "Per capita income means?", options: ["Total income of a country", "Average income per person", "Tax collected", "Export value"], correct: 1 },
  { text: "What does 'currency devaluation' mean?", options: ["Currency value decreases", "Currency value increases", "No change", "Currency banned"], correct: 0 },
  { text: "Which sector includes farming?", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Quaternary sector"], correct: 0 },
  { text: "Which sector includes manufacturing?", options: ["Primary sector", "Secondary sector", "Tertiary sector", "None"], correct: 1 },
  { text: "Which sector includes services like banking?", options: ["Primary sector", "Secondary sector", "Tertiary sector", "None"], correct: 2 },
  { text: "What is 'Repo Rate'?", options: ["Rate RBI lends to banks", "Rate banks lend to customers", "Tax rate", "Exchange rate"], correct: 0 },
  { text: "What does 'export' mean?", options: ["Buying from other countries", "Selling to other countries", "Internal trade", "Tax collection"], correct: 1 },
  { text: "What does 'import' mean?", options: ["Buying from other countries", "Selling to other countries", "Internal trade", "Tax collection"], correct: 0 },
  { text: "Which is a direct tax?", options: ["Income Tax", "GST", "Excise Duty", "Customs Duty"], correct: 0 },
  { text: "Which is an indirect tax?", options: ["Income Tax", "GST", "Wealth Tax", "Corporate Tax"], correct: 1 },
  { text: "What is 'recession'?", options: ["Economic growth", "Economic decline", "Stable economy", "High employment"], correct: 1 },
  { text: "Which body issues currency notes in India?", options: ["SBI", "RBI", "Finance Ministry", "SEBI"], correct: 1 },
  { text: "What is 'unemployment rate'?", options: ["% of people without jobs", "% of people with jobs", "Total population", "GDP growth"], correct: 0 },
  { text: "Stock exchange in Mumbai is called?", options: ["NSE", "BSE", "NYSE", "LSE"], correct: 1 },
  { text: "Which is India's National Stock Exchange?", options: ["BSE", "NSE", "NYSE", "LSE"], correct: 1 },
  { text: "What does 'subsidy' mean?", options: ["Tax on goods", "Financial aid by govt", "Export tax", "Import ban"], correct: 1 }
];