const songsQuestions = [
  { text: "National Anthem of India was written by?", options: ["Bankim Chandra", "Rabindranath Tagore", "Sarojini Naidu", "Subhash Bose"], correct: 1 },
  { text: "Which instrument has strings?", options: ["Flute", "Guitar", "Drum", "Trumpet"], correct: 1 },
  { text: "A song's rhythm pattern is called?", options: ["Melody", "Tempo", "Beat", "Pitch"], correct: 2 },
  { text: "National Song 'Vande Mataram' was written by?", options: ["Tagore", "Bankim Chandra Chattopadhyay", "Iqbal", "Premchand"], correct: 1 },
  { text: "Sitar is a type of?", options: ["Wind instrument", "String instrument", "Percussion", "Brass"], correct: 1 },
  { text: "Tabla is played by?", options: ["Blowing", "Strumming", "Hitting/Tapping", "Bowing"], correct: 2 },
  { text: "Which is a classical Indian dance form with music?", options: ["Bharatanatyam", "Ballet", "Salsa", "Hip-hop"], correct: 0 },
  { text: "Lata Mangeshkar was famous as a?", options: ["Actress", "Playback Singer", "Dancer", "Director"], correct: 1 },
  { text: "Harmonium is played using?", options: ["Strings", "Keys and air pump", "Drumsticks", "Bow"], correct: 1 },
  { text: "A.R. Rahman is famous for?", options: ["Acting", "Music Composing", "Direction", "Writing"], correct: 1 },
  { text: "Violin is played with a?", options: ["Pick", "Bow", "Stick", "Hammer"], correct: 1 },
  { text: "Which is a percussion instrument?", options: ["Flute", "Guitar", "Drums", "Violin"], correct: 2 },
  { text: "Carnatic music is mainly from which region?", options: ["North India", "South India", "East India", "West India"], correct: 1 },
  { text: "Hindustani classical music is from?", options: ["South India", "North India", "East India", "Central India"], correct: 1 },
  { text: "A group singing together is called?", options: ["Solo", "Duet", "Choir", "Orchestra only"], correct: 2 },
  { text: "Which instrument is also called 'Mouth Organ'?", options: ["Harmonica", "Flute", "Trumpet", "Clarinet"], correct: 0 },
  { text: "Raga in Indian music refers to?", options: ["A dance step", "A melodic framework", "A drum beat", "An instrument"], correct: 1 },
  { text: "Which is India's national song (not anthem)?", options: ["Jana Gana Mana", "Vande Mataram", "Saare Jahan Se Achha", "Ae Mere Watan"], correct: 1 },
  { text: "Guitar strings are usually how many?", options: ["4", "5", "6", "7"], correct: 2 },
  { text: "Which is a wind instrument?", options: ["Flute", "Guitar", "Drum", "Sitar"], correct: 0 },
  { text: "Piano keys are played using?", options: ["Bow", "Fingers", "Drumsticks", "Pick"], correct: 1 },
  { text: "Which legendary singer sang 'Thriller'?", options: ["Elvis Presley", "Michael Jackson", "Freddie Mercury", "Prince"], correct: 1 },
  { text: "Who composed India's National Anthem's tune?", options: ["Bankim Chandra", "Rabindranath Tagore", "Lata Mangeshkar", "A.R. Rahman"], correct: 1 },
  { text: "Which is a stringed Indian classical instrument?", options: ["Tabla", "Sitar", "Dhol", "Manjira"], correct: 1 },
  { text: "A 'duet' means singing by how many people?", options: ["1", "2", "3", "A group"], correct: 1 },
  { text: "Which band sang 'Bohemian Rhapsody'?", options: ["The Beatles", "Queen", "ABBA", "Pink Floyd"], correct: 1 },
  { text: "Flute is played by?", options: ["Blowing", "Strumming", "Hitting", "Bowing"], correct: 0 },
  { text: "Which is a traditional Punjabi instrument?", options: ["Dhol", "Sitar", "Veena", "Santoor"], correct: 0 },
  { text: "Veena is mainly used in which music style?", options: ["Hindustani", "Carnatic", "Western", "Jazz"], correct: 1 },
  { text: "Who is known as the 'King of Pop'?", options: ["Elvis Presley", "Michael Jackson", "Justin Bieber", "Prince"], correct: 1 }
];