const sportsQuestions = [
  { text: "Which sport is called 'The Gentleman's Game'?", options: ["Football", "Cricket", "Hockey", "Tennis"], correct: 1 },
  { text: "How many players in a football team?", options: ["9", "10", "11", "12"], correct: 2 },
  { text: "Olympics are held every how many years?", options: ["2", "3", "4", "5"], correct: 2 },
  { text: "Which country won FIFA World Cup 2022?", options: ["Brazil", "France", "Argentina", "Germany"], correct: 2 },
  { text: "How many players in a cricket team?", options: ["9", "10", "11", "12"], correct: 2 },
  { text: "Badminton shuttle is made of?", options: ["Plastic", "Feathers", "Rubber", "Cloth"], correct: 1 },
  { text: "Which sport uses a 'puck'?", options: ["Hockey", "Ice Hockey", "Golf", "Polo"], correct: 1 },
  { text: "Sachin Tendulkar is related to which sport?", options: ["Hockey", "Cricket", "Football", "Badminton"], correct: 1 },
  { text: "Wimbledon is related to which sport?", options: ["Tennis", "Golf", "Cricket", "Rugby"], correct: 0 },
  { text: "How many rings in Olympic flag?", options: ["4", "5", "6", "7"], correct: 1 },
  { text: "Which country invented Kabaddi?", options: ["Pakistan", "India", "Bangladesh", "Nepal"], correct: 1 },
  { text: "Usain Bolt is famous for?", options: ["Swimming", "Sprinting", "Boxing", "Cycling"], correct: 1 },
  { text: "A 'century' in cricket means?", options: ["100 balls", "100 runs", "100 wickets", "100 overs"], correct: 1 },
  { text: "Which sport is played at Wimbledon on grass?", options: ["Tennis", "Cricket", "Football", "Hockey"], correct: 0 },
  { text: "FIFA is related to which sport?", options: ["Basketball", "Football", "Cricket", "Hockey"], correct: 1 },
  { text: "Which country hosts 2026 FIFA World Cup?", options: ["Qatar", "USA/Canada/Mexico", "Brazil", "Germany"], correct: 1 },
  { text: "A basketball court has how many hoops?", options: ["1", "2", "3", "4"], correct: 1 },
  { text: "Chess board has how many squares?", options: ["32", "48", "64", "100"], correct: 2 },
  { text: "Golf ball is hit with a?", options: ["Bat", "Racket", "Club", "Stick"], correct: 2 },
  { text: "Which sport is Lionel Messi famous in?", options: ["Cricket", "Football", "Tennis", "Hockey"], correct: 1 },
  { text: "Boxing ring is actually what shape?", options: ["Circle", "Square", "Triangle", "Oval"], correct: 1 },
  { text: "Which sport uses term 'LBW'?", options: ["Football", "Cricket", "Hockey", "Badminton"], correct: 1 },
  { text: "Table tennis is also called?", options: ["Ping pong", "Lawn tennis", "Squash", "Badminton"], correct: 0 },
  { text: "Which country is famous for Sumo wrestling?", options: ["China", "Japan", "Korea", "Thailand"], correct: 1 },
  { text: "How many sets to win in men's tennis Grand Slam?", options: ["2", "3", "4", "5"], correct: 1 },
  { text: "Which sport has term 'Checkmate'?", options: ["Carrom", "Chess", "Ludo", "Cards"], correct: 1 },
  { text: "Rugby originated in which country?", options: ["USA", "England", "Australia", "France"], correct: 1 },
  { text: "Which sport is known as 'King of Sports'?", options: ["Cricket", "Football", "Hockey", "Tennis"], correct: 1 },
  { text: "Swimming pool length in Olympics is?", options: ["25m", "50m", "100m", "75m"], correct: 1 },
  { text: "Which equipment is used in archery?", options: ["Bat", "Bow", "Racket", "Club"], correct: 1 }
];