const templesQuestions = [
  { text: "Which temple is known as 'Golden Temple'?", options: ["Tirupati", "Harmandir Sahib", "Meenakshi", "Kashi Vishwanath"], correct: 1 },
  { text: "Khajuraho temples are famous for?", options: ["Carvings", "Height", "Color", "Gold"], correct: 0 },
  { text: "Konark Sun Temple is in which state?", options: ["Bihar", "Odisha", "Kerala", "Punjab"], correct: 1 },
  { text: "Golden Temple is located in?", options: ["Delhi", "Amritsar", "Mumbai", "Chennai"], correct: 1 },
  { text: "Tirupati Balaji temple is in which state?", options: ["Tamil Nadu", "Andhra Pradesh", "Karnataka", "Kerala"], correct: 1 },
  { text: "Meenakshi Temple is located in?", options: ["Madurai", "Mysore", "Kochi", "Hyderabad"], correct: 0 },
  { text: "Kedarnath Temple is dedicated to?", options: ["Vishnu", "Shiva", "Brahma", "Ganesha"], correct: 1 },
  { text: "Which temple has 12 Jyotirlingas related sites?", options: ["Shiva temples", "Vishnu temples", "Durga temples", "Ganesha temples"], correct: 0 },
  { text: "Akshardham Temple is located in?", options: ["Mumbai", "Delhi", "Jaipur", "Pune"], correct: 1 },
  { text: "Jagannath Temple is located in?", options: ["Puri", "Konark", "Bhubaneswar", "Cuttack"], correct: 0 },
  { text: "Somnath Temple is in which state?", options: ["Gujarat", "Rajasthan", "Maharashtra", "Goa"], correct: 0 },
  { text: "Which temple is a UNESCO World Heritage Site in Odisha?", options: ["Jagannath", "Konark Sun Temple", "Lingaraj", "Mukteshwar"], correct: 1 },
  { text: "Brihadeeswarar Temple is located in?", options: ["Thanjavur", "Chennai", "Madurai", "Trichy"], correct: 0 },
  { text: "Vaishno Devi shrine is in which state?", options: ["Himachal Pradesh", "Jammu & Kashmir", "Uttarakhand", "Punjab"], correct: 1 },
  { text: "Which temple is dedicated to Lord Venkateswara?", options: ["Tirupati", "Somnath", "Kedarnath", "Badrinath"], correct: 0 },
  { text: "Lingaraj Temple is located in?", options: ["Puri", "Bhubaneswar", "Cuttack", "Konark"], correct: 1 },
  { text: "Siddhivinayak Temple is located in?", options: ["Pune", "Mumbai", "Nashik", "Nagpur"], correct: 1 },
  { text: "Amarnath Cave Temple is dedicated to?", options: ["Vishnu", "Shiva", "Durga", "Hanuman"], correct: 1 },
  { text: "Dilwara Temples are located in?", options: ["Mount Abu", "Udaipur", "Jaisalmer", "Jodhpur"], correct: 0 },
  { text: "Which temple complex is in Hampi?", options: ["Virupaksha Temple", "Meenakshi Temple", "Jagannath Temple", "Somnath Temple"], correct: 0 },
  { text: "Kashi Vishwanath Temple is in which city?", options: ["Varanasi", "Allahabad", "Ayodhya", "Mathura"], correct: 0 },
  { text: "Which temple is famous for Rath Yatra festival?", options: ["Jagannath Temple", "Meenakshi Temple", "Somnath Temple", "Akshardham"], correct: 0 },
  { text: "Ranakpur Jain Temple is in which state?", options: ["Gujarat", "Rajasthan", "MP", "Maharashtra"], correct: 1 },
  { text: "Badrinath Temple is dedicated to?", options: ["Shiva", "Vishnu", "Brahma", "Durga"], correct: 1 },
  { text: "Golden Temple's holy pool is called?", options: ["Amrit Sarovar", "Ganga Sarovar", "Shiv Sarovar", "Brahma Sarovar"], correct: 0 },
  { text: "Which temple has the Dancing Hall (Natya Mandapa)?", options: ["Konark Sun Temple", "Somnath Temple", "Kashi Vishwanath", "Badrinath"], correct: 0 },
  { text: "Padmanabhaswamy Temple is located in?", options: ["Kochi", "Thiruvananthapuram", "Kozhikode", "Kottayam"], correct: 1 },
  { text: "Which temple is known for erotic sculptures?", options: ["Khajuraho", "Konark", "Meenakshi", "Somnath"], correct: 0 },
  { text: "Mahakaleshwar Temple is located in?", options: ["Ujjain", "Indore", "Bhopal", "Gwalior"], correct: 0 },
  { text: "Which is India's tallest temple tower (Gopuram)?", options: ["Thillai Nataraja", "Srirangam Ranganathaswamy", "Meenakshi", "Brihadeeswarar"], correct: 1 }
];